options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Install dependencies
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci  # Faster and safer than `npm install`
        npm install -g @angular/cli firebase-tools

  # 2️⃣ Build Angular app
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build -- --configuration=production

  # 3️⃣ Deploy to Firebase Hosting
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        firebase deploy --only hosting --project $PROJECT_ID
