options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🏗️ 1️⃣ Install dependencies
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm install -g @angular/cli

  # 🏗️ 2️⃣ Build the Angular frontend
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build -- --configuration=production

  # 🚀 3️⃣ Install Firebase CLI and Deploy to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project $PROJECT_ID
