steps:
  # 🏗️ Install Dependencies & Build
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build -- --configuration=production

  # 🚀 Deploy to Firebase Hosting (Ensure Firebase CLI is Installed in the Same Step)
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --token "$$FIREBASE_TOKEN"
    secretEnv: ['FIREBASE_TOKEN']

availableSecrets:
  secretManager:
    - env: "FIREBASE_TOKEN"
      versionName: "projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest"

options:
  logging: CLOUD_LOGGING_ONLY
